sudo: required
dist: trusty
language: cpp

env:
  global:
    - /usr/local/bin:$PATH

cache:
  directories:
    - $HOME/.bazel-output-base
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - CXX_COMPILER="g++-5"
        - C_COMPILER="gcc-5"
    - os: osx
      osx_image: xcode9
      compiler: clang
      env:
        - CXX_COMPILER="clang++"
        - C_COMPILER="clang"

install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo add-apt-repository ppa:dreal/dreal -y;
      sudo apt update;
      sudo apt install autoconf automake bison coinor-libclp-dev flex libtool pkg-config libibex-dev libnlopt-dev;
      wget https://dl.bintray.com/dreal/dreal/dreal_4.18.01.3_amd64.deb;
      sudo dpkg -i dreal_4.18.01.3_amd64.deb;
    fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      brew update;
      brew install dreal/dreal/dreal || true;
    fi

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} ../
  - make           
  - ./check_sat

notifications:
  recipients:
    - soonho.kong@gmail.com
  email:
    on_success: change
    on_failure: always

